version: "3.8"

services:
  mongodb:
    image: bitnami/mongodb:4.4
    container_name: ol-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  mongo:
